### ISSUE TITLE
Test conformation sampling using waymarking without limiting to only the 1st .dcd file

### ISSUE THREAD

**Issue by JatGreer** [ccpem/roodmus#1]
Issue 9 from gitlab 
Test conformation sampling using waymarking without limiting to only the 1st .dcd file

**Comment by MJoosten** [comment]
Currently, the waymarking option does not work when a single trajectory file is provided. Filtering of conformations only occurs when the second file is loaded. I have not tested if the function works with a second trajectory file addded.

A more pressing issue is that the waymarking is done by comparing all conformations in the trajectory to the first conformation, and filtering out conformations that are closer to the initial conformations (by rmsd) then a user defined threhshold. This means there is still a large oversampling of states, as 2 conformations that are not close to the initial conformation, but are close to eachother would both be retained.

For the time being, I will remove the waymarking feature from the conformations_sampling script as an option, while leaving the functions in. I think that it may be useful to redo the waymarking in the future in a slightly different way.
